import {assets} from './assets.mjs';
import {buildChecks,canPass,fileType} from './checks.mjs';
const LIMIT=12*1024*1024;
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers}});
const err=(message,status=400)=>Object.assign(new Error(message),{status});
const stmt=(env,sql,...args)=>env.DB.prepare(sql).bind(...args);
const one=(env,sql,...args)=>stmt(env,sql,...args).first();
const rows=async(env,sql,...args)=>(await stmt(env,sql,...args).all()).results;
const now=()=>new Date().toISOString();
const id=()=>crypto.randomUUID();
const hash=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(b=>b.toString(16).padStart(2,'0')).join('');
function identity(req,env){const pid=req.headers.get('oai-authenticated-user-id');if(pid)return {id:pid,email:req.headers.get('oai-authenticated-user-email')||''};const url=new URL(req.url);if(env.LOCAL_DEVELOPMENT==='true'&&['localhost','127.0.0.1'].includes(url.hostname))return {id:'local-test-officer',email:'local-preview@example.invalid'};return null;}
function cookie(req,value,maxAge){return `sd_session=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${maxAge}${new URL(req.url).protocol==='https:'?'; Secure':''}`;}
async function auth(req,env){const ident=identity(req,env);const token=req.headers.get('Cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('sd_session='))?.slice(11);if(!ident||!token)throw err('Sign in to your officer workspace.',401);const officer=await one(env,'SELECT o.* FROM sessions s JOIN officers o ON o.id=s.officer_id WHERE s.token_hash=? AND s.expires_at>? AND o.platform_id=?',await hash(token),Date.now(),ident.id);if(!officer)throw err('Your session has expired. Sign in again.',401);return officer;}
async function owned(env,officer,caseId){const c=await one(env,'SELECT * FROM cases WHERE id=?',caseId);if(!c||(c.owner_id!==officer.id&&officer.role!=='supervisor'))throw err('Case not found or access unavailable.',404);return c;}
function event(env,officer,caseId,action,detail=''){return stmt(env,'INSERT INTO events (id,case_id,officer_id,action,detail,created_at) VALUES (?,?,?,?,?,?)',id(),caseId,officer.id,action,detail,now());}
async function input(env,caseId){const captures=await rows(env,'SELECT * FROM captures WHERE case_id=? ORDER BY created_at DESC',caseId);const f=await one(env,'SELECT * FROM fields WHERE case_id=?',caseId);return {captures,fields:f?JSON.parse(f.data):{},revision:await hash(JSON.stringify({captures:captures.filter(c=>!c.superseded).map(c=>c.id).sort(),fields:f?.data||''}))};}
async function detail(env,officer,caseId){const c=await owned(env,officer,caseId);const v=await input(env,caseId);const run=await one(env,'SELECT * FROM runs WHERE case_id=? ORDER BY created_at DESC LIMIT 1',caseId);return {case:c,captures:v.captures.map(({object_key,...c})=>({...c,url:`/api/captures/${c.id}`})),fields:v.fields,checks:run?JSON.parse(run.results):[],checksStale:!!run&&run.input_revision!==v.revision,run:run?{id:run.id,status:run.status,created_at:run.created_at}:null,events:await rows(env,'SELECT e.*,o.name AS officer_name FROM events e JOIN officers o ON o.id=e.officer_id WHERE e.case_id=? ORDER BY e.created_at DESC LIMIT 100',caseId),decisions:await rows(env,'SELECT d.*,o.name AS officer_name FROM decisions d JOIN officers o ON o.id=d.officer_id WHERE d.case_id=? ORDER BY d.created_at DESC',caseId)};}
async function body(req){if(Number(req.headers.get('Content-Length')||0)>65536)throw err('Request is too large.',413);let b;try{b=await req.json()}catch{throw err('Invalid request data.')}if(!b||typeof b!=='object'||Array.isArray(b))throw err('Invalid request data.');return b;}
const clean=(value,max=200)=>String(value??'').trim().slice(0,max);
async function api(req,env,url){
 if(!env.DB||!env.BUCKET)throw err('Workspace storage is unavailable. Your changes have not been saved.',503);
 if(!['GET','HEAD'].includes(req.method)&&req.headers.get('Origin')!==url.origin)throw err('This request must come from the SeemaDrishti workspace.',403);
 if(url.pathname==='/api/access'&&req.method==='GET'){const ident=identity(req,env);if(!ident)return json({authenticated:false});const o=await one(env,'SELECT name,officer_code,checkpoint FROM officers WHERE platform_id=?',ident.id);return json({authenticated:true,profile:o,email:ident.email});}
 if(url.pathname==='/api/login'&&req.method==='POST'){
  const ident=identity(req,env);if(!ident)throw err('Use the secure sign-in link to continue.',401);
  let officer=await one(env,'SELECT * FROM officers WHERE platform_id=?',ident.id);
  if(!officer){const b=await body(req);const name=clean(b.name,100),code=clean(b.officerCode,40),checkpoint=clean(b.checkpoint,100);if(name.length<2||!code||!checkpoint)throw err('Enter your name, officer ID and checkpoint.');if(!/^[a-zA-Z0-9 _-]{2,40}$/.test(code))throw err('Use letters, numbers, spaces or hyphens for the officer ID.');const existing=await one(env,'SELECT id FROM officers WHERE officer_code=?',code);if(existing)throw err('That officer ID is already registered.',409);const officerId=id();await stmt(env,'INSERT INTO officers (id,platform_id,officer_code,name,checkpoint,role,created_at) VALUES (?,?,?,?,?,?,?)',officerId,ident.id,code,name,checkpoint,'officer',now()).run();officer=await one(env,'SELECT * FROM officers WHERE id=?',officerId);}
  const token=id()+id();await env.DB.batch([stmt(env,'DELETE FROM sessions WHERE officer_id=? OR expires_at<?',officer.id,Date.now()),stmt(env,'INSERT INTO sessions (token_hash,officer_id,expires_at) VALUES (?,?,?)',await hash(token),officer.id,Date.now()+8*3600000)]);return json({officer:publicOfficer(officer)},200,{'Set-Cookie':cookie(req,token,28800)});
 }
 const officer=await auth(req,env);
 if(url.pathname==='/api/me'&&req.method==='GET')return json({officer:publicOfficer(officer)});
 if(url.pathname==='/api/logout'&&req.method==='POST'){await stmt(env,'DELETE FROM sessions WHERE officer_id=?',officer.id).run();return json({ok:true},200,{'Set-Cookie':cookie(req,'',0)});}
 if(url.pathname==='/api/cases'&&req.method==='GET'){const list=officer.role==='supervisor'?await rows(env,'SELECT c.*,o.name AS officer_name FROM cases c JOIN officers o ON o.id=c.owner_id ORDER BY c.updated_at DESC LIMIT 500'):await rows(env,'SELECT * FROM cases WHERE owner_id=? ORDER BY updated_at DESC LIMIT 500',officer.id);return json({cases:list});}
 if(url.pathname==='/api/cases'&&req.method==='POST'){const b=await body(req);const caseId='SD-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+id().slice(0,8).toUpperCase(),t=now();await env.DB.batch([stmt(env,'INSERT INTO cases (id,owner_id,traveller_name,reference,status,stage,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)',caseId,officer.id,clean(b.travellerName,150),clean(b.reference,100),'draft','documents',t,t),event(env,officer,caseId,'Case created')]);return json({id:caseId},201);}
 const caseMatch=url.pathname.match(/^\/api\/cases\/([^/]+)(?:\/(fields|captures|checks|decision|stage))?$/);
 if(caseMatch){const caseId=caseMatch[1],action=caseMatch[2];const c=await owned(env,officer,caseId);
  if(!action&&req.method==='GET')return json(await detail(env,officer,caseId));
  if(action==='stage'&&req.method==='POST'){const b=await body(req);if(!['documents','face','review'].includes(b.stage))throw err('Invalid workflow stage.');await stmt(env,'UPDATE cases SET stage=? WHERE id=?',b.stage,caseId).run();return json({ok:true});}
  if(action==='fields'&&req.method==='POST'){const b=await body(req);const data={};for(const key of ['passportName','passportNumber','nationality','passportDob','passportExpiry','visaName','visaNumber','visaDob','visaType','visaExpiry'])data[key]=clean(b[key],150);const t=now();await env.DB.batch([stmt(env,'INSERT INTO fields (case_id,data,source,updated_at) VALUES (?,?,?,?) ON CONFLICT(case_id) DO UPDATE SET data=excluded.data,source=excluded.source,updated_at=excluded.updated_at',caseId,JSON.stringify(data),'officer_entered',t),stmt(env,"UPDATE cases SET traveller_name=?,updated_at=?,status='draft' WHERE id=?",data.passportName||data.visaName||c.traveller_name,t,caseId),event(env,officer,caseId,'Document fields saved','Officer-entered values; OCR not performed')]);return json({ok:true});}
  if(action==='captures'&&req.method==='POST'){
   if(Number(req.headers.get('Content-Length')||0)>LIMIT+65536)throw err('Choose a file smaller than 12 MB.',413);
   const data=await req.formData(),file=data.get('file'),kind=data.get('kind'),docType=clean(data.get('documentType'),40),source=data.get('source');
   if(!file||typeof file.arrayBuffer!=='function'||!file.size)throw err('Select a document or capture an image.');if(file.size>LIMIT)throw err('Choose a file smaller than 12 MB.',413);
   if(!['document','face'].includes(kind)||!['upload','camera','scanner'].includes(source))throw err('Unsupported capture source.');if(kind==='face'&&source!=='camera')throw err('Use the live camera to capture the traveller’s face.');
   if(kind==='document'&&!['passport','visa','national_id','permit','driving_license','other'].includes(docType))throw err('Choose a document type.');
   const bytes=new Uint8Array(await file.arrayBuffer()),mime=fileType(bytes);if(!mime||(kind==='face'&&mime==='application/pdf'))throw err('Use a JPEG, PNG, WebP image or a PDF document.');
   const captureId=id(),key=`${officer.id}/${caseId}/${captureId}`,t=now();await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:mime}});
   try{await env.DB.batch([stmt(env,'UPDATE captures SET superseded=1 WHERE case_id=? AND kind=? AND document_type=?',caseId,kind,kind==='face'?'face':docType),stmt(env,'INSERT INTO captures (id,case_id,kind,document_type,source,filename,mime,object_key,size,superseded,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)',captureId,caseId,kind,kind==='face'?'face':docType,source,clean(file.name,150),mime,key,file.size,0,t),stmt(env,"UPDATE cases SET updated_at=?,status='draft' WHERE id=?",t,caseId),event(env,officer,caseId,kind==='face'?'Face capture saved':'Document saved',`${kind==='face'?'Live camera':docType} · ${source}`)]);}catch(e){await env.BUCKET.delete(key);throw e;}return json({id:captureId},201);
  }
  if(action==='checks'&&req.method==='POST'){const v=await input(env,caseId),checks=buildChecks(v.captures,v.fields),status=checks.some(x=>x.state==='flagged')?'flagged':'awaiting_review',t=now();await env.DB.batch([stmt(env,'INSERT INTO runs (id,case_id,results,status,input_revision,created_at) VALUES (?,?,?,?,?,?)',id(),caseId,JSON.stringify(checks),status,v.revision,t),stmt(env,"UPDATE cases SET status=?,stage='review',updated_at=? WHERE id=?",status,t,caseId),event(env,officer,caseId,'Available checks evaluated','File presence and officer-entered field rules only; AI checks not connected')]);return json(await detail(env,officer,caseId));}
  if(action==='decision'&&req.method==='POST'){const b=await body(req);const actions={recapture:'recapture_needed',supervisor:'supervisor_review',note:'awaiting_review',pass:'completed'};if(!Object.hasOwn(actions,b.action))throw err('Choose an officer action.');const reason=clean(b.reason,1000);if(reason.length<5)throw err('Record a reason of at least 5 characters.');if(b.action==='pass'){const v=await input(env,caseId),run=await one(env,'SELECT * FROM runs WHERE case_id=? ORDER BY created_at DESC LIMIT 1',caseId);if(!run||run.input_revision!==v.revision||!canPass(JSON.parse(run.results)))throw err('Required checks are incomplete. This case cannot be marked passed.',409);}const t=now();await env.DB.batch([stmt(env,'INSERT INTO decisions (id,case_id,officer_id,action,reason,created_at) VALUES (?,?,?,?,?,?)',id(),caseId,officer.id,b.action,reason,t),stmt(env,'UPDATE cases SET status=?,updated_at=? WHERE id=?',actions[b.action],t,caseId),event(env,officer,caseId,'Officer action recorded',`${b.action}: ${reason}`)]);return json({ok:true});}
 }
 const captureMatch=url.pathname.match(/^\/api\/captures\/([^/]+)$/);if(captureMatch&&req.method==='GET'){const file=await one(env,'SELECT * FROM captures WHERE id=?',captureMatch[1]);if(!file)throw err('Capture not found.',404);await owned(env,officer,file.case_id);const object=await env.BUCKET.get(file.object_key);if(!object)throw err('Capture file is unavailable.',404);return new Response(object.body,{headers:{'Content-Type':file.mime,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Disposition':`inline; filename="${file.filename.replace(/[^\w. -]/g,'_')}"`}});}
 throw err('Endpoint not found.',404);
}
function publicOfficer(o){return {id:o.id,name:o.name,officerCode:o.officer_code,checkpoint:o.checkpoint,role:o.role};}
export default {async fetch(req,env){const url=new URL(req.url);let response;try{if(url.pathname.startsWith('/api/'))response=await api(req,env,url);else{const asset=assets[url.pathname==='/'?'/index.html':url.pathname];response=asset?new Response(asset.body,{headers:{'Content-Type':asset.type,'Cache-Control':'no-cache'}}):new Response('Not found',{status:404});}}catch(e){if(!e.status)console.error('Workspace request failed',e.message);response=json({error:e.status?e.message:'Unable to save or load workspace data. Please retry; unsaved input remains on this page.'},e.status||503);}const headers=new Headers(response.headers);headers.set('X-Content-Type-Options','nosniff');headers.set('Referrer-Policy','same-origin');headers.set('Permissions-Policy','camera=(self), microphone=()');return new Response(response.body,{status:response.status,headers});}};
