import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const officers = sqliteTable('officers', {id:text('id').primaryKey(), platformId:text('platform_id').notNull(), officerCode:text('officer_code').notNull(), name:text('name').notNull(), checkpoint:text('checkpoint').notNull(), role:text('role').notNull().default('officer'), createdAt:text('created_at').notNull()},t=>[uniqueIndex('officers_platform_idx').on(t.platformId),uniqueIndex('officers_code_idx').on(t.officerCode)]);
export const sessions = sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),officerId:text('officer_id').notNull().references(()=>officers.id),expiresAt:integer('expires_at').notNull()});
export const cases = sqliteTable('cases',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>officers.id),travellerName:text('traveller_name').notNull().default(''),reference:text('reference').notNull().default(''),status:text('status').notNull().default('draft'),stage:text('stage').notNull().default('documents'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('cases_owner_updated_idx').on(t.ownerId,t.updatedAt)]);
export const captures = sqliteTable('captures',{id:text('id').primaryKey(),caseId:text('case_id').notNull().references(()=>cases.id),kind:text('kind').notNull(),documentType:text('document_type').notNull(),source:text('source').notNull(),filename:text('filename').notNull(),mime:text('mime').notNull(),objectKey:text('object_key').notNull(),size:integer('size').notNull(),superseded:integer('superseded').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('captures_case_idx').on(t.caseId)]);
export const fields = sqliteTable('fields',{caseId:text('case_id').primaryKey().references(()=>cases.id),data:text('data').notNull(),source:text('source').notNull().default('officer_entered'),updatedAt:text('updated_at').notNull()});
export const runs = sqliteTable('runs',{id:text('id').primaryKey(),caseId:text('case_id').notNull().references(()=>cases.id),results:text('results').notNull(),status:text('status').notNull(),inputRevision:text('input_revision').notNull(),createdAt:text('created_at').notNull()},t=>[index('runs_case_created_idx').on(t.caseId,t.createdAt)]);
export const decisions = sqliteTable('decisions',{id:text('id').primaryKey(),caseId:text('case_id').notNull().references(()=>cases.id),officerId:text('officer_id').notNull().references(()=>officers.id),action:text('action').notNull(),reason:text('reason').notNull(),createdAt:text('created_at').notNull()},t=>[index('decisions_case_idx').on(t.caseId)]);
export const events = sqliteTable('events',{id:text('id').primaryKey(),caseId:text('case_id').notNull().references(()=>cases.id),officerId:text('officer_id').notNull().references(()=>officers.id),action:text('action').notNull(),detail:text('detail').notNull(),createdAt:text('created_at').notNull()},t=>[index('events_case_created_idx').on(t.caseId,t.createdAt)]);
